name: Benchmarks

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Set up Rust (Nightly)
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly

      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run Benchmarks
        run: cargo bench --locked
      
      - name: Worker info
        run: |-
          cat /proc/cpuinfo
          cat /proc/meminfo